### ISSUE TITLE
ES6 code published to npm?

### ISSUE THREAD

**Issue by pwagner** [aaron9000/react-image-timeline#1]
I was running into problems (related to browserify/babelify), because apparently the code was not compiled from ES6 to ES5 before publishing it to npm.

**Comment by aaron9000** [comment]
Good catch & thank you.

I will address that today.

**Comment by pwagner** [comment]
Awesome, I would love to use your timeline for a project. Thanks for the great effort!

**Comment by aaron9000** [comment]
@pwagner - I *think* I fixed your issue. Can you confirm?

You will need to `require` the CSS yourself now. I made a poor assumption about how CSS is referenced in node projects.

**Comment by pwagner** [comment]
Yes, I confirm, thank you very much!
As you said, I just had to include to CSS myself.

**Comment by aaron9000** [comment]
Thank you, sir.

Leave me a star if you get good use out of react-image-timeline
