### ISSUE TITLE
Example Project throws TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by Ckimchris** [aaron9000/react-image-timeline#25]
Here is the error I run into after npm run script on the Example Project. 

TypeError: Object(...) is not a function
> 68 | ) => {
     | ^  69 |   const [imageType, setImageType] = useState('normal');
  70 |   const [events, setEvents] = useState(getSampleData(imageType));
  71 |   const [useCustomComponents, setUseCustomComponents] = useState(false);`

**Comment by aaron9000** [comment]
Did you run `yarn` after cloning the repository? And do you have `create-react-app` installed?

You may need something like this before running the example project:
`npm install -g create-react-app`

I will make sure these steps are clearer in the README.

Let me know if this solves your issue.

**Comment by aaron9000** [comment]
Also try `yarn --debug` to install any dev dependencies that may be missing.

I released a new version of the library a few moments ago.
