### ISSUE TITLE
Can I adjust the distance between two points

### ISSUE THREAD

**Issue by guangming21** [aaron9000/react-image-timeline#5]
now it is
![qq 20161011165635](https://cloud.githubusercontent.com/assets/18028721/19264545/b8724058-8fd3-11e6-9177-29926fd38c37.png)
The distance is too long

**Comment by aaron9000** [comment]
@guangming21 

Yes, you are going to have to customize the SCSS / CSS. The images in your timeline appear to be very small. Simply making them larger may be a better solution.

I believe you will need to modify the variable `$min-event-height: 620px;`. (possibly others)
https://github.com/aaron9000/react-image-timeline/blob/master/lib/timeline.scss

I hope this helps.

**Comment by guangming21** [comment]
@aaron9000ok, thanks. can you update this, because when i deploy my project, it will auto download the component, so the change will return to the old style

**Comment by aaron9000** [comment]
You can copy the css file and import that instead of the bundled css. Then you can make as many edits as you like.

**Comment by guangming21** [comment]
ok， i will ,thank you

**Comment by aaron9000** [comment]
Let me know if this fixes your problem!

Consider leaving me a star if you find the library useful.

**Comment by guangming21** [comment]
It's done

**Comment by aaron9000** [comment]
👍
