### ISSUE TITLE
React 16 and PropTypes

### ISSUE THREAD

**Issue by levantainteractive** [aaron9000/react-image-timeline#6]
Hello, I'm getting an error related to the use of PropTypes in React 16+. Are you planning on updating the codebase? If so, here's an article to look at,

https://reactjs.org/warnings/dont-call-proptypes.html

**Comment by aaron9000** [comment]
I will attempt to update this weekend - apologies for the delayed response!

**Comment by aaron9000** [comment]
This should be fixed now @levantainteractive. It's a Create React App project now.
