### ISSUE TITLE
Issue In Default Setup

### ISSUE THREAD

**Issue by spina-a-d** [aaron9000/react-image-timeline#8]
I followed a really default setup from the `npm` page to see how it worked, but I think there's an issue with how the date is parsed.

This simple code:

```
<Timeline events={[{
                date: Date.parse("2013-09-27"),
                text: "Sed leo elit, pellentesque sit amet congue quis, ornare nec lorem.",
                title: "Cairo, Egypt",
                imageUrl: "http://github.com/aaron9000/react-image-timeline/blob/master/src/assets/cairo.jpg?raw=true"
}]} />
```

Produces the error:

```
TypeError: e.getFullYear is not a function
```

I would suspect something is going wrong if this basic example fails.

**Comment by spina-a-d** [comment]
Update:  I can get other date objects to work, so I think the example code just needs updating.

**Comment by aaron9000** [comment]
Thank you! I will fix this weekend.

**Comment by aaron9000** [comment]
What kind of date object did you pass?

I should probably add some validation and more helpful errors.

**Comment by spina-a-d** [comment]
@aaron9000 When I got the error I did the date as I showed in the above snippet.  When I got it to work I think I did it with `new Date('27-09-2013')` or something similar instead.  I can't confirm because I no longer have the code I was testing with.

**Comment by aaron9000** [comment]
You are right. Date.parse() is not producing a date object.

**Comment by aaron9000** [comment]
@spina-a-d closing now. I put out a new version of the package and addressed the incorrect setup instructions. Appreciate you taking the time to file an issue! 👍
